Website: "https://discord.petropia.net"
Spawn:
  X: -1.5
  Y: 105.5
  Z: -3.5
  Pitch: 0
  Yaw: 86

MinigamePortals:
  CL_Solo:
    X1: -71
    Y1: 100
    Z1: -85
    X2: -70
    Y2: 102
    Z2: -89
    Game: "CHICKEN_LEAGUE"
    Mode: "SINGLE"
  CL_Team:
    X1: -92
    Y1: 100
    Z1: -85
    X2: -93
    Y2: 102
    Z2: -89
    Game: "CHICKEN_LEAGUE"
    Mode: "MULTI"
  Bingo_Team:
    X1: -6
    Y1: 106
    Z1: -90
    X2: -5
    Y2: 117
    Z2: -89
    Game: "Bingo"
    Mode: "DUO"
  Bingo_Solo:
    X1: -8
    Y1: 117
    Z1: -89
    X2: -9
    Y2: 106
    Z2: -90
    Game: "Bingo"
    Mode: "SINGLE"

Locations:
  Spacelife:
    X: -100
    Y: 104.1
    Z: 0
    Yaw: 90
    Pitch: -10
  Bingo:
    X: -6.5
    Y: 106
    Z: -83.5
    Yaw: -180
    Pitch: 1
  ChickenLeague:
    X: -70.5
    Y: 100
    Z: -73.5
    Yaw: 140
    Pitch: 0

Holograms:
  Spacelife:
    X: -33.5
    Y: 103.5
    Z: -1.5
    Text: "<bold><gold>Spacelife<br><reset><gray>Farme in der Farmwelt Böcke und Geld, baue das schönste Grundstück oder werde mit deinem Shop Reich. Unser Freebuild-, SkyBlock- und Economymodus"
    Item: "GOLDEN_APPLE"
    Group: "Spacelife"
    Offset: 2.2
  Bingo:
    X: -6.5
    Y: 103.5
    Z: -49.5
    Text: "<bold><gold>Bingo<br><reset><gray>Finde alleine oder als Duo 5 Items in einer Reihe auf der Bingokarte und endecke jede Runde eine neue zufällige Minecraft Welt"
    Item: "PAPER"
    Group: "Bingo"
    Offset: 1.9
  ChickenLeague:
    X: -22.5
    Y: 103.5
    Z: -47.5
    Text: "<bold><gold>ChickenLeague<br><reset><gray>Spiele alleine oder im Team mit einem Huhn Fußball. Verwende verschiedene Schläger um deinen Gegner zu besiegen oder halte deinen Gegner mit verschiedenen Specialitems auf"
    Item: "WOODEN_SHOVEL"
    Group: "ChickenLeague"
    Offset: 2.2
