Spawn:
  X: -1.5
  Y: 105.5
  Z: -3.5
  Pitch: 0
  Yaw: 86

MinigamePortals:
  CL_Solo:
    X1: -71
    Y1: 100
    Z1: -85
    X2: -70
    Y2: 102
    Z2: -89
    Game: "CHICKEN_LEAGUE"
    Mode: "SINGLE"
  CL_Team:
    X1: -92
    Y1: 100
    Z1: -85
    X2: -93
    Y2: 102
    Z2: -89
    Game: "CHICKEN_LEAGUE"
    Mode: "MULTI"
  Bingo_Team:
    X1: -6
    Y1: 106
    Z1: -90
    X2: -5
    Y2: 117
    Z2: -89
    Game: "Bingo"
    Mode: "DUO"
  Bingo_Solo:
    X1: -8
    Y1: 117
    Z1: -89
    X2: -9
    Y2: 106
    Z2: -90
    Game: "Bingo"
    Mode: "SINGLE"

